(function(){'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const valid=p=>p.length>=8&&/[A-Za-z]/.test(p)&&/\d/.test(p)&&/[^A-Za-z0-9]/.test(p);
function css(){if(document.getElementById('pm-css'))return;const s=document.createElement('style');s.id='pm-css';s.textContent='#pm{position:fixed;inset:0;z-index:1000;background:#042318aa;display:none;place-items:center;padding:16px}#pm .pmc{width:min(470px,100%);background:#fff;border-radius:18px;padding:20px;box-shadow:0 25px 70px #0004}#pm h2{margin:0 0 5px}#pm label{display:block;font-size:12px;font-weight:800;margin:12px 0 5px}#pm input{width:100%;padding:11px;border:1px solid var(--line);border-radius:9px;font:inherit}#pm .pma{display:flex;gap:8px;margin-top:14px}#pm .pma button{flex:1;padding:11px;border:0;border-radius:9px;font-weight:800}.pm-save{background:var(--g);color:#fff}.pm-cancel{background:#edf4f0;color:var(--g)}.pm-note{font-size:11px;color:var(--muted);margin-top:5px}.pm-msg{margin-top:9px}.pm-change{white-space:nowrap}@media(max-width:600px){.pm-change{font-size:11px!important;padding:8px 9px!important}}';document.head.appendChild(s)}
function modal(){if(document.getElementById('pm'))return;const d=document.createElement('div');d.id='pm';d.innerHTML='<div class="pmc"><h2>Change password</h2><p class="muted">Change your learner or teacher password securely.</p><div id="pmCurrentWrap"><label>Current / temporary password</label><input id="pmCurrent" type="password" autocomplete="current-password"></div><label>New password</label><input id="pmNew" type="password" autocomplete="new-password"><label>Confirm new password</label><input id="pmConfirm" type="password" autocomplete="new-password"><div class="pm-note">At least 8 characters with a letter, number and special character.</div><div id="pmMsg" class="pm-msg"></div><div class="pma"><button class="pm-cancel" onclick="closePasswordChange()">Cancel</button><button class="pm-save" onclick="savePasswordChange()">Change password</button></div></div>';document.body.appendChild(d)}
window.openPasswordChange=function(recovery){css();modal();window.__pmRecovery=!!recovery;document.getElementById('pm').style.display='grid';document.getElementById('pmCurrentWrap').style.display=recovery?'none':'block';document.getElementById('pmMsg').innerHTML=recovery?'<div class="notice"><b>Password recovery session active.</b><br>Choose your new password.</div>':'';['pmCurrent','pmNew','pmConfirm'].forEach(id=>document.getElementById(id).value='')};
window.closePasswordChange=function(){const d=document.getElementById('pm');if(d)d.style.display='none';window.__pmRecovery=false};
window.savePasswordChange=async function(){const cur=document.getElementById('pmCurrent').value,n=document.getElementById('pmNew').value,c=document.getElementById('pmConfirm').value,m=document.getElementById('pmMsg');if(!valid(n)){m.innerHTML='<div class="login-error">New password must be at least 8 characters and contain letters, numbers and a special character.</div>';return}if(n!==c){m.innerHTML='<div class="login-error">The new passwords do not match.</div>';return}if(!window.__pmRecovery&&!cur){m.innerHTML='<div class="login-error">Enter your current or temporary password.</div>';return}m.innerHTML='<div class="notice">Updating password securely…</div>';try{const {error}=window.__pmRecovery?await sb.auth.updateUser({password:n}):await sb.auth.updateUser({password:n,current_password:cur});if(error)throw error;m.innerHTML='<div class="feedback good"><b>Password changed successfully.</b><br>Your new password is now active.</div>';setTimeout(closePasswordChange,1200)}catch(e){m.innerHTML='<div class="login-error">'+esc(e.message||'Unable to change password.')+'</div>'}};
function add(){const a=document.querySelector('.top-actions'),o=document.getElementById('loginOverlay');if(!a||!o||o.style.display==='grid'||o.style.display===''||document.getElementById('pmBtn'))return;const b=document.createElement('button');b.id='pmBtn';b.className='btn alt pm-change';b.type='button';b.textContent='🔐 Change password';b.onclick=()=>openPasswordChange(false);a.insertBefore(b,a.firstChild)}
function patchForgot(){if(window.__pmForgot||typeof window.forgotPassword!=='function')return;window.__pmForgot=true;window.forgotPassword=async function(){const id=(document.getElementById('loginUsername')?.value||'').trim(),m=document.getElementById('loginMessage');if(!id){m.innerHTML='<div class="login-error">Enter your username or email first.</div>';return}m.innerHTML='<div class="notice">Requesting password-reset email…</div>';try{const res=await fetch(gatewayUrl(),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'reset',identifier:id,redirectTo:location.href.split('#')[0]})}),d=await res.json().catch(()=>({}));if(!res.ok)throw Error(d.error||'Password reset could not be requested.');m.innerHTML='<div class="notice"><b>Reset request processed.</b><br>Check inbox and spam/junk. If no email arrives, the Supabase email provider must be configured for this learner/teacher address.</div>'}catch(e){m.innerHTML='<div class="login-error">'+esc(e.message||'Password reset could not be requested.')+'</div>'}}}
function watch(){css();modal();patchForgot();add()}
document.addEventListener('DOMContentLoaded',()=>{watch();setTimeout(watch,500);setInterval(watch,1500);if(typeof sb!=='undefined')sb.auth.onAuthStateChange(e=>{if(e==='PASSWORD_RECOVERY')setTimeout(()=>openPasswordChange(true),250)})});
})();
