const CACHE='isdlss-v20260822-12';
const ASSETS=['./','./index.html','./manifest.webmanifest','./module-assessment.js','./assessment-loader.js'];
self.addEventListener('install',event=>{self.skipWaiting();event.waitUntil(caches.open(CACHE).then(c=>c.addAll(ASSETS)).catch(()=>{}));});
self.addEventListener('activate',event=>{event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim()));});
self.addEventListener('fetch',event=>{const req=event.request;if(req.method!=='GET')return;const url=new URL(req.url);if(url.origin!==location.origin)return;
 if(req.mode==='navigate'||url.pathname.endsWith('/index.html')){event.respondWith(fetch(req,{cache:'no-store'}).then(async response=>{const text=await response.clone().text();let injected=text;const stamp='20260822-module-assessment-v3';const loader='<script src="assessment-loader.js?v='+stamp+'" defer data-assessment-loader></script>';if(!injected.includes('data-assessment-loader'))injected=injected.replace('</head>',loader+'</head>');const headers=new Headers(response.headers);headers.set('content-type','text/html; charset=utf-8');headers.delete('content-length');return new Response(injected,{status:response.status,statusText:response.statusText,headers});}).catch(()=>caches.match('./index.html')));return;}
 if(url.pathname.endsWith('/module-assessment.js')||url.pathname.endsWith('/assessment-loader.js')){event.respondWith(fetch(req,{cache:'no-store'}).then(response=>{if(response.ok)caches.open(CACHE).then(c=>c.put(req,response.clone())).catch(()=>{});return response;}).catch(()=>caches.match(req)));return;}
 event.respondWith(caches.match(req).then(cached=>cached||fetch(req).then(response=>{if(response.ok)caches.open(CACHE).then(c=>c.put(req,response.clone())).catch(()=>{});return response;}).catch(()=>cached)));
});
