-- Seed the 20-question lesson-level formative assessment for Agricultural Machinery and Farm Safety.
insert into public.quiz_questions (module_id, lesson_id, question, options, correct_answer, points, position)
select 'c86df66b-5e83-4c11-b714-a9a182df92ec'::uuid, v.lesson_id, v.question, v.options::jsonb, v.correct_answer, 1, v.position
from (values
('b86ee68e-c9dd-4dec-ae09-718b74f5ac66'::uuid,'Which machine is commonly used to plough or turn soil before planting?','["Plough","Milking machine","Sprayer","Grain cleaner"]','Plough',1),
('b86ee68e-c9dd-4dec-ae09-718b74f5ac66'::uuid,'What is the main purpose of a harrow?','["Break soil clods and prepare the seedbed","Pump water into a tank","Harvest milk","Store harvested grain"]','Break soil clods and prepare the seedbed',2),
('b86ee68e-c9dd-4dec-ae09-718b74f5ac66'::uuid,'Which machine is primarily used to apply pesticides or liquid chemicals evenly to crops?','["Sprayer","Plough","Trailer","Thresher"]','Sprayer',3),
('b86ee68e-c9dd-4dec-ae09-718b74f5ac66'::uuid,'Why should an operator read the machinery manual before use?','["To understand safe operation and correct procedures","To increase the machine weight","To avoid all maintenance","To replace protective equipment"]','To understand safe operation and correct procedures',4),
('b86ee68e-c9dd-4dec-ae09-718b74f5ac66'::uuid,'Which action is safest before servicing a powered machine?','["Switch it off, isolate the power source and secure it","Leave the engine running","Remove guards while it is moving","Ask another person to hold the moving parts"]','Switch it off, isolate the power source and secure it',5),
('b86ee68e-c9dd-4dec-ae09-718b74f5ac66'::uuid,'What is the main purpose of a machine guard?','["To protect people from moving or dangerous parts","To make the machine louder","To increase fuel consumption","To replace operator training"]','To protect people from moving or dangerous parts',6),
('b86ee68e-c9dd-4dec-ae09-718b74f5ac66'::uuid,'Which personal protective equipment is especially appropriate when operating machinery that creates loud noise?','["Hearing protection","Open sandals","Loose jewellery","A necktie"]','Hearing protection',7),
('b86ee68e-c9dd-4dec-ae09-718b74f5ac66'::uuid,'Loose clothing and jewellery are dangerous around moving machinery because they can:','["Become caught in moving parts","Improve machine efficiency","Reduce fuel use","Prevent all injuries"]','Become caught in moving parts',8),
('b86ee68e-c9dd-4dec-ae09-718b74f5ac66'::uuid,'Which practice helps prevent machinery breakdowns?','["Regular inspection and preventive maintenance","Ignoring unusual sounds","Overloading the machine","Using the wrong lubricant"]','Regular inspection and preventive maintenance',9),
('b86ee68e-c9dd-4dec-ae09-718b74f5ac66'::uuid,'What should an operator do if a machine develops an unusual vibration while working?','["Stop safely and investigate or report the problem","Increase the speed","Continue until the work is finished","Remove the safety guard while running"]','Stop safely and investigate or report the problem',10),
('b86ee68e-c9dd-4dec-ae09-718b74f5ac66'::uuid,'Which factor is important when selecting machinery for a farm?','["Farm size, enterprise needs and available resources","Colour of the machine only","The loudest engine available","The largest machine regardless of need"]','Farm size, enterprise needs and available resources',11),
('b86ee68e-c9dd-4dec-ae09-718b74f5ac66'::uuid,'Why can choosing machinery that is too large for a small farm be inefficient?','["It may have unnecessary purchase, fuel and maintenance costs","It always produces less power","It cannot be maintained","It cannot perform any farm task"]','It may have unnecessary purchase, fuel and maintenance costs',12),
('b86ee68e-c9dd-4dec-ae09-718b74f5ac66'::uuid,'Which action can improve fuel efficiency when operating farm machinery?','["Keep the machine properly maintained and operate it appropriately","Run the engine at maximum speed at all times","Ignore tyre pressure","Carry unnecessary loads"]','Keep the machine properly maintained and operate it appropriately',13),
('b86ee68e-c9dd-4dec-ae09-718b74f5ac66'::uuid,'What is a major safety risk when refuelling machinery?','["Fire caused by fuel contacting an ignition source","Improved engine cooling","Better soil fertility","Reduced noise"]','Fire caused by fuel contacting an ignition source',14),
('b86ee68e-c9dd-4dec-ae09-718b74f5ac66'::uuid,'Where should fuel and other hazardous chemicals generally be stored?','["In a suitable, secure and well-managed storage area","Beside an open flame","Inside the tractor cab","In an unlabelled drinking-water bottle"]','In a suitable, secure and well-managed storage area',15),
('b86ee68e-c9dd-4dec-ae09-718b74f5ac66'::uuid,'Why is operator training important for farm machinery?','["It helps the operator use the machine safely and correctly","It removes the need for maintenance","It guarantees no accidents can ever occur","It makes protective equipment unnecessary"]','It helps the operator use the machine safely and correctly',16),
('b86ee68e-c9dd-4dec-ae09-718b74f5ac66'::uuid,'Which practice reduces the risk of an accident when reversing a tractor or other large machine?','["Check the area carefully and use appropriate visibility or assistance","Reverse at maximum speed","Ignore blind spots","Allow children to stand behind the machine"]','Check the area carefully and use appropriate visibility or assistance',17),
('b86ee68e-c9dd-4dec-ae09-718b74f5ac66'::uuid,'Why should machinery be cleaned after appropriate use?','["To remove dirt or residues that can contribute to wear or damage","To make the engine consume more fuel","To eliminate the need for inspections","To sharpen every machine part"]','To remove dirt or residues that can contribute to wear or damage',18),
('b86ee68e-c9dd-4dec-ae09-718b74f5ac66'::uuid,'What is the best general response to a machinery accident or near miss?','["Stop, make the area safe, report it and learn from the incident","Hide the incident","Restart immediately without checking","Blame another worker and continue"]','Stop, make the area safe, report it and learn from the incident',19),
('b86ee68e-c9dd-4dec-ae09-718b74f5ac66'::uuid,'Which statement best describes safe and sustainable machinery management?','["Select suitable equipment, operate it safely, maintain it well and use resources efficiently","Use the largest machine regardless of need","Avoid all maintenance to save money","Operate machines without training or protective measures"]','Select suitable equipment, operate it safely, maintain it well and use resources efficiently',20)
) as v(lesson_id,question,options,correct_answer,position)
where not exists (select 1 from public.quiz_questions q where q.lesson_id=v.lesson_id and q.position=v.position);
