-- Initial LMS schema for Supabase project vahkwyetointavhzwfef.
-- Reconstructed from the current IS-DLSS LMS frontend requirements.
-- Keep this migration in GitHub as the source of truth for the database.

create extension if not exists pgcrypto;

do $$ begin create type public.app_role as enum ('Administrator','Teacher','Student'); exception when duplicate_object then null; end $$;
do $$ begin create type public.course_status as enum ('Draft','Active','Published','Archived'); exception when duplicate_object then null; end $$;

create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, username text not null unique, full_name text not null default 'New User', role public.app_role not null default 'Student', institution text, active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.courses (id uuid primary key default gen_random_uuid(), title text not null, description text, status public.course_status not null default 'Draft', instructor_id uuid references public.profiles(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.modules (id uuid primary key default gen_random_uuid(), course_id uuid not null references public.courses(id) on delete cascade, title text not null, description text, position integer not null default 1 check(position>0), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(course_id,position));
create table if not exists public.lessons (id uuid primary key default gen_random_uuid(), module_id uuid not null references public.modules(id) on delete cascade, title text not null, content text not null default '', video_url text, position integer not null default 1 check(position>0), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(module_id,position));
create table if not exists public.course_enrolments (id uuid primary key default gen_random_uuid(), course_id uuid not null references public.courses(id) on delete cascade, student_id uuid not null references public.profiles(id) on delete cascade, enrolled_at timestamptz not null default now(), active boolean not null default true, unique(course_id,student_id));
create table if not exists public.student_progress (id uuid primary key default gen_random_uuid(), student_id uuid not null references public.profiles(id) on delete cascade, course_id uuid not null references public.courses(id) on delete cascade, progress_percent numeric(5,2) not null default 0 check(progress_percent between 0 and 100), updated_at timestamptz not null default now(), unique(student_id,course_id));
create table if not exists public.lesson_progress (id uuid primary key default gen_random_uuid(), student_id uuid not null references public.profiles(id) on delete cascade, lesson_id uuid not null references public.lessons(id) on delete cascade, completed boolean not null default false, completed_at timestamptz, updated_at timestamptz not null default now(), unique(student_id,lesson_id));
create table if not exists public.quiz_questions (id uuid primary key default gen_random_uuid(), module_id uuid not null references public.modules(id) on delete cascade, question text not null, options jsonb not null default '[]'::jsonb, correct_answer text not null, points numeric(8,2) not null default 1 check(points>0), position integer not null default 1 check(position>0), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(module_id,position));
create table if not exists public.quiz_attempts (id uuid primary key default gen_random_uuid(), module_id uuid not null references public.modules(id) on delete cascade, student_id uuid not null references public.profiles(id) on delete cascade, answers jsonb not null default '{}'::jsonb, score numeric(10,2) not null default 0, max_score numeric(10,2) not null default 0, client_submission_id text unique, submitted_at timestamptz not null default now());
create table if not exists public.assessment_feedback (id uuid primary key default gen_random_uuid(), attempt_id uuid not null unique references public.quiz_attempts(id) on delete cascade, reviewer_id uuid not null references public.profiles(id) on delete restrict, feedback text not null, strengths text, improvement_area text, action_plan text, updated_at timestamptz not null default now(), created_at timestamptz not null default now());
create table if not exists public.notifications (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, type text not null, title text not null, message text not null, entity_id uuid, read_at timestamptz, created_at timestamptz not null default now());
create table if not exists public.discussion_posts (id uuid primary key default gen_random_uuid(), author_id uuid not null references public.profiles(id) on delete cascade, course_id uuid references public.courses(id) on delete set null, body text not null check(length(trim(body)) between 1 and 2000), created_at timestamptz not null default now());
create table if not exists public.video_resources (id uuid primary key default gen_random_uuid(), title text not null, youtube_id text not null, description text, course_id uuid references public.courses(id) on delete set null, created_at timestamptz not null default now());
create or replace view public.assessment_attempts as select * from public.quiz_attempts;

create index if not exists idx_courses_instructor on public.courses(instructor_id);
create index if not exists idx_modules_course on public.modules(course_id,position);
create index if not exists idx_lessons_module on public.lessons(module_id,position);
create index if not exists idx_enrolments_student on public.course_enrolments(student_id);
create index if not exists idx_enrolments_course on public.course_enrolments(course_id);
create index if not exists idx_progress_student on public.student_progress(student_id);
create index if not exists idx_lesson_progress_student on public.lesson_progress(student_id);
create index if not exists idx_questions_module on public.quiz_questions(module_id,position);
create index if not exists idx_attempts_student on public.quiz_attempts(student_id,submitted_at desc);
create index if not exists idx_attempts_module on public.quiz_attempts(module_id);
create index if not exists idx_feedback_attempt on public.assessment_feedback(attempt_id);
create index if not exists idx_notifications_user on public.notifications(user_id,created_at desc);
create index if not exists idx_discussions_course on public.discussion_posts(course_id,created_at desc);

create or replace function public.set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end $$;

drop trigger if exists trg_profiles_updated on public.profiles; create trigger trg_profiles_updated before update on public.profiles for each row execute function public.set_updated_at();
drop trigger if exists trg_courses_updated on public.courses; create trigger trg_courses_updated before update on public.courses for each row execute function public.set_updated_at();
drop trigger if exists trg_modules_updated on public.modules; create trigger trg_modules_updated before update on public.modules for each row execute function public.set_updated_at();
drop trigger if exists trg_lessons_updated on public.lessons; create trigger trg_lessons_updated before update on public.lessons for each row execute function public.set_updated_at();
drop trigger if exists trg_progress_updated on public.student_progress; create trigger trg_progress_updated before update on public.student_progress for each row execute function public.set_updated_at();
drop trigger if exists trg_lesson_progress_updated on public.lesson_progress; create trigger trg_lesson_progress_updated before update on public.lesson_progress for each row execute function public.set_updated_at();
drop trigger if exists trg_questions_updated on public.quiz_questions; create trigger trg_questions_updated before update on public.quiz_questions for each row execute function public.set_updated_at();

create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.profiles where id=auth.uid() and role='Administrator' and active); $$;
create or replace function public.is_teacher_of_course(p_course_id uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.profiles p join public.courses c on c.instructor_id=p.id where p.id=auth.uid() and p.role='Teacher' and p.active and c.id=p_course_id); $$;

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,username,full_name,role,institution) values(new.id,coalesce(new.raw_user_meta_data->>'username',split_part(new.email,'@',1)),coalesce(new.raw_user_meta_data->>'full_name','New User'),'Student'::public.app_role,new.raw_user_meta_data->>'institution') on conflict(id) do nothing; return new; end $$;
drop trigger if exists on_auth_user_created on auth.users; create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

create or replace function public.recalculate_quiz_attempt_score() returns trigger language plpgsql security definer set search_path=public as $$ declare total numeric:=0; earned numeric:=0; q record; selected text; begin select coalesce(sum(points),0) into total from public.quiz_questions where module_id=new.module_id; for q in select id,correct_answer,points from public.quiz_questions where module_id=new.module_id loop selected:=new.answers->>q.id::text; if selected is not null and selected=q.correct_answer then earned:=earned+q.points; end if; end loop; new.max_score:=total; new.score:=earned; return new; end $$;
drop trigger if exists trg_quiz_score on public.quiz_attempts; create trigger trg_quiz_score before insert or update of answers,module_id on public.quiz_attempts for each row execute function public.recalculate_quiz_attempt_score();

create or replace function public.student_quiz_questions(p_module_id uuid) returns table(id uuid,question text,options jsonb,points numeric,"position" integer) language sql stable security definer set search_path=public as $$ select q.id,q.question,q.options,q.points,q.position from public.quiz_questions q join public.modules m on m.id=q.module_id join public.course_enrolments e on e.course_id=m.course_id and e.student_id=auth.uid() join public.profiles p on p.id=auth.uid() where q.module_id=p_module_id and p.role='Student' and p.active order by q.position; $$;
create or replace function public.teacher_supervision_students(p_teacher_id uuid) returns table(student_id uuid,student_name text,student_username text,course_id uuid,course_title text,progress_percent numeric,latest_score numeric,latest_max_score numeric) language sql stable security definer set search_path=public as $$ select e.student_id,sp.full_name,sp.username,c.id,c.title,coalesce(prog.progress_percent,0),qa.score,qa.max_score from public.course_enrolments e join public.courses c on c.id=e.course_id and c.instructor_id=p_teacher_id join public.profiles sp on sp.id=e.student_id and sp.role='Student' and sp.active left join public.student_progress prog on prog.student_id=e.student_id and prog.course_id=c.id left join lateral (select a.score,a.max_score from public.quiz_attempts a join public.modules mm on mm.id=a.module_id where a.student_id=e.student_id and mm.course_id=c.id order by a.submitted_at desc limit 1) qa on true where p_teacher_id=auth.uid() or public.is_admin(); $$;
create or replace function public.submit_module_quiz(p_module_id uuid,p_course_id uuid,p_answers text) returns public.quiz_attempts language plpgsql security definer set search_path=public as $$ declare result public.quiz_attempts; begin if auth.uid() is null then raise exception 'Authentication required'; end if; if not exists(select 1 from public.course_enrolments where course_id=p_course_id and student_id=auth.uid()) then raise exception 'Student is not enrolled in this course'; end if; insert into public.quiz_attempts(module_id,student_id,answers) values(p_module_id,auth.uid(),p_answers::jsonb) returning * into result; return result; end $$;

alter table public.profiles enable row level security; alter table public.courses enable row level security; alter table public.modules enable row level security; alter table public.lessons enable row level security; alter table public.course_enrolments enable row level security; alter table public.student_progress enable row level security; alter table public.lesson_progress enable row level security; alter table public.quiz_questions enable row level security; alter table public.quiz_attempts enable row level security; alter table public.assessment_feedback enable row level security; alter table public.notifications enable row level security; alter table public.discussion_posts enable row level security; alter table public.video_resources enable row level security;

create policy profiles_self_read on public.profiles for select to authenticated using(id=auth.uid() or public.is_admin() or exists(select 1 from public.courses c join public.course_enrolments e on e.course_id=c.id where c.instructor_id=auth.uid() and e.student_id=profiles.id));
create policy profiles_admin_manage on public.profiles for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy courses_read on public.courses for select to authenticated using(status in ('Active','Published') or public.is_admin() or instructor_id=auth.uid() or exists(select 1 from public.course_enrolments e where e.course_id=courses.id and e.student_id=auth.uid()));
create policy courses_admin_manage on public.courses for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy courses_teacher_manage on public.courses for all to authenticated using(instructor_id=auth.uid() and exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='Teacher' and p.active)) with check(instructor_id=auth.uid());
create policy modules_read on public.modules for select to authenticated using(public.is_admin() or exists(select 1 from public.courses c where c.id=modules.course_id and (c.instructor_id=auth.uid() or c.status in ('Active','Published') or exists(select 1 from public.course_enrolments e where e.course_id=c.id and e.student_id=auth.uid()))));
create policy modules_manage on public.modules for all to authenticated using(public.is_admin() or public.is_teacher_of_course(course_id)) with check(public.is_admin() or public.is_teacher_of_course(course_id));
create policy lessons_read on public.lessons for select to authenticated using(public.is_admin() or exists(select 1 from public.modules m join public.courses c on c.id=m.course_id where m.id=lessons.module_id and (c.instructor_id=auth.uid() or c.status in ('Active','Published') or exists(select 1 from public.course_enrolments e where e.course_id=c.id and e.student_id=auth.uid()))));
create policy lessons_manage on public.lessons for all to authenticated using(public.is_admin() or exists(select 1 from public.modules m where m.id=lessons.module_id and public.is_teacher_of_course(m.course_id))) with check(public.is_admin() or exists(select 1 from public.modules m where m.id=lessons.module_id and public.is_teacher_of_course(m.course_id)));
create policy enrolments_read on public.course_enrolments for select to authenticated using(student_id=auth.uid() or public.is_admin() or exists(select 1 from public.courses c where c.id=course_enrolments.course_id and c.instructor_id=auth.uid()));
create policy enrolments_manage on public.course_enrolments for all to authenticated using(public.is_admin() or exists(select 1 from public.courses c where c.id=course_enrolments.course_id and c.instructor_id=auth.uid())) with check(public.is_admin() or exists(select 1 from public.courses c where c.id=course_enrolments.course_id and c.instructor_id=auth.uid()));
create policy progress_read on public.student_progress for select to authenticated using(student_id=auth.uid() or public.is_admin() or exists(select 1 from public.courses c where c.id=student_progress.course_id and c.instructor_id=auth.uid()));
create policy progress_student_write on public.student_progress for insert to authenticated with check(student_id=auth.uid() and exists(select 1 from public.course_enrolments e where e.course_id=student_progress.course_id and e.student_id=auth.uid()));
create policy progress_student_update on public.student_progress for update to authenticated using(student_id=auth.uid()) with check(student_id=auth.uid() and exists(select 1 from public.course_enrolments e where e.course_id=student_progress.course_id and e.student_id=auth.uid()));
create policy progress_admin_manage on public.student_progress for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy lesson_progress_read on public.lesson_progress for select to authenticated using(student_id=auth.uid() or public.is_admin() or exists(select 1 from public.lessons l join public.modules m on m.id=l.module_id join public.courses c on c.id=m.course_id where l.id=lesson_progress.lesson_id and c.instructor_id=auth.uid()));
create policy lesson_progress_student_write on public.lesson_progress for insert to authenticated with check(student_id=auth.uid() and exists(select 1 from public.lessons l join public.modules m on m.id=l.module_id join public.course_enrolments e on e.course_id=m.course_id and e.student_id=auth.uid() where l.id=lesson_progress.lesson_id));
create policy lesson_progress_student_update on public.lesson_progress for update to authenticated using(student_id=auth.uid()) with check(student_id=auth.uid() and exists(select 1 from public.lessons l join public.modules m on m.id=l.module_id join public.course_enrolments e on e.course_id=m.course_id and e.student_id=auth.uid() where l.id=lesson_progress.lesson_id));
create policy lesson_progress_admin_manage on public.lesson_progress for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy quiz_questions_teacher_admin on public.quiz_questions for select to authenticated using(public.is_admin() or exists(select 1 from public.modules m where m.id=quiz_questions.module_id and public.is_teacher_of_course(m.course_id)));
create policy quiz_questions_manage on public.quiz_questions for all to authenticated using(public.is_admin() or exists(select 1 from public.modules m where m.id=quiz_questions.module_id and public.is_teacher_of_course(m.course_id))) with check(public.is_admin() or exists(select 1 from public.modules m where m.id=quiz_questions.module_id and public.is_teacher_of_course(m.course_id)));
create policy attempts_read on public.quiz_attempts for select to authenticated using(student_id=auth.uid() or public.is_admin() or exists(select 1 from public.modules m where m.id=quiz_attempts.module_id and public.is_teacher_of_course(m.course_id)));
create policy attempts_student_insert on public.quiz_attempts for insert to authenticated with check(student_id=auth.uid() and exists(select 1 from public.modules m join public.courses c on c.id=m.course_id join public.course_enrolments e on e.course_id=c.id and e.student_id=auth.uid() where m.id=quiz_attempts.module_id and c.status in ('Active','Published')));
create policy attempts_admin_manage on public.quiz_attempts for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy feedback_read on public.assessment_feedback for select to authenticated using(exists(select 1 from public.quiz_attempts a where a.id=assessment_feedback.attempt_id and (a.student_id=auth.uid() or public.is_admin() or exists(select 1 from public.modules m where m.id=a.module_id and public.is_teacher_of_course(m.course_id)))));
create policy feedback_manage on public.assessment_feedback for all to authenticated using(public.is_admin() or reviewer_id=auth.uid()) with check(public.is_admin() or reviewer_id=auth.uid());
create policy notifications_self on public.notifications for select to authenticated using(user_id=auth.uid());
create policy notifications_update_self on public.notifications for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy notifications_insert_admin on public.notifications for insert to authenticated with check(public.is_admin() or user_id=auth.uid());
create policy discussions_read on public.discussion_posts for select to authenticated using(true);
create policy discussions_insert on public.discussion_posts for insert to authenticated with check(author_id=auth.uid());
create policy discussions_update on public.discussion_posts for update to authenticated using(author_id=auth.uid() or public.is_admin()) with check(author_id=auth.uid() or public.is_admin());
create policy discussions_delete on public.discussion_posts for delete to authenticated using(author_id=auth.uid() or public.is_admin());
create policy videos_read on public.video_resources for select to authenticated using(true);
create policy videos_manage on public.video_resources for all to authenticated using(public.is_admin() or public.is_teacher_of_course(course_id)) with check(public.is_admin() or public.is_teacher_of_course(course_id));

revoke all on function public.rls_auto_enable() from public,anon,authenticated;
revoke all on function public.handle_new_user() from public,anon,authenticated;
revoke all on function public.recalculate_quiz_attempt_score() from public,anon,authenticated;
revoke all on function public.submit_module_quiz(uuid,uuid,text) from public,anon,authenticated;
revoke all on function public.is_admin() from public,anon;
revoke all on function public.is_teacher_of_course(uuid) from public,anon;
revoke all on function public.teacher_supervision_students(uuid) from public,anon; grant execute on function public.teacher_supervision_students(uuid) to authenticated;
revoke all on function public.student_quiz_questions(uuid) from public,anon; grant execute on function public.student_quiz_questions(uuid) to authenticated;
